name: CI/CD Pipeline Completo

# Se ejecuta cuando hacemos push a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TRABAJO 1: PRUEBAS (Continuous Integration)
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Obtener código (Checkout)
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Instalar dependencias de prueba
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Ejecutar Pruebas Unitarias
      run: |
        python -m unittest discover tests

  # TRABAJO 2: CONSTRUCCIÓN DEL PAQUETE (Continuous Delivery)
  build:
    needs: test  # Solo se ejecuta si 'test' pasa correctamente
    runs-on: ubuntu-latest
    steps:
    - name: Obtener código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Instalar herramientas de construcción
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Construir el Paquete (Artifact)
      run: python -m build

    - name: Guardar el Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: paquete-distribuible
        path: dist/